### ISSUE TITLE
imageのmanifestを取る際に適切に認証できるようにしてほしい

### ISSUE THREAD

**Issue by kory33** [sksat/compose-cd#20]
例えば ghcr.io の private image の manifest を取るなどが現状できないので、これができるようになるとうれしい　pullは各自docker loginしておけばよいため追加の対応は不要ぽい

**Comment by sksat** [comment]
https://himenon.github.io/docs/docker/registry-api/

**Comment by sksat** [comment]
まずはPATというか`docker login`をするところからだなー

**Comment by sksat** [comment]
`docker login`は責任範囲外だろ！と思ったんですが(いやまあregistry, username, password全部同じでいいならそれでいいんだけど)，そうでもないなあ

**Comment by sksat** [comment]
`/etc/compose-cd/config`にdefault username/passwordを入れておき，`repo/.compose-cd`にPAT相当のやつとか入れるかんじでいくかねえ

**Comment by sksat** [comment]
PATでやるやつ，ここに`-u "username:${PAT}"`を追加すればいいということが分かった．

https://github.com/sksat/compose-cd/blob/ace8c84dd0c447236315b400599244a15f0577c3/compose-cd#L123-L125

**Comment by sksat** [comment]
別に無を突っ込んでも怒られないしこれでいいな

**Comment by sksat** [comment]
説
- https://github.com/github/roadmap/issues/350

_Originally posted by @sksat in https://github.com/sksat/compose-cd/issues/22#issuecomment-995511275_
