### ISSUE TITLE
`compose-cd install` 時、SEARCH_ROOT等がすでに設定されていれば聞かれないようにしたい

### ISSUE THREAD

**Issue by kory33** [sksat/compose-cd#26]
`source /etc/compose-cd/config` したうえでenvに値があればそれを使う、とかやっても良さそう

**Comment by sksat** [comment]
それはね、思っていました

**Comment by kory33** [comment]
顧客が本当に欲しかったもの情報です(from https://github.com/sksat/compose-cd/pull/27#discussion_r782796438)

> 我々のuse-caseでは変数の入力の手間を減らすために一部設定を「決め打ちしておきたい」みたいな要求があり

現在[このようにしている](https://github.com/GiganticMinecraft/seichi_infra/blob/d3ffdbfe96272d160ae8fbcfff4181b6a8e3efd8/seichi-onp-network-iap/setup-server.sh#L6-L9)のでこれが渡ってほしいというやつでした（渡した分の入力は省略されてほしい）。この要求の正しい解決法はconfigを読みに行かせるというよりパラメータの一部を渡せるoptionを追加するというやつっぽい

**それとは並行して**、すでに `compose-cd install` が行われている場合に再入力を省略させるオプションというのがあっても良さそう？要るか？(GiganticMinecraftでは多分使わない)

**Comment by sksat** [comment]
> `source /etc/compose-cd/config` したうえでenvに値があればそれを使う、とかやっても良さそう

これが認識の齟齬の元っぽい

**Comment by sksat** [comment]
> 正しい解決法はconfigを読みに行かせるというよりパラメータの一部を渡せるoptionを追加する

そうだと思う．あとゆるふわな名前の環境変数読みに行くのは破壊を生みがちなので，やるとしても読むやつは`COMPOSE_CD_`みたいなprefixを付けるとかしたいかなあ．

**Comment by sksat** [comment]
> それとは並行して、すでに compose-cd install が行われている場合に再入力を省略させるオプションというのがあっても良さそう？要るか？(GiganticMinecraftでは多分使わない)

元々思っていたのにやっていなかったのはそんなことやり始めたら絶対に僕という怠け者がサボって知らんうちに破滅が起きかねないので毎回入力させる手間を踏ませるという意図があったのでこれは要らないかなあ．ansible/itamaeとかでプロビショニングする用途でもそこで変な状態持ちたくないし．

**Comment by kory33** [comment]
> > それとは並行して、すでに compose-cd install が行われている場合に再入力を省略させるオプションというのがあっても良さそう？要るか？(GiganticMinecraftでは多分使わない)
> 
> 
> 
> 元々思っていたのにやっていなかったのはそんなことやり始めたら絶対に僕という怠け者がサボって知らんうちに破滅が起きかねないので毎回入力させる手間を踏ませるという意図があったのでこれは要らないかなあ．ansible/itamaeとかでプロビショニングする用途でもそこで変な状態持ちたくないし．

じゃあこれはなしで　我々も使わないし状態として持たれるのはあんまり嬉しいケースなさそう

**Comment by kory33** [comment]
> > 正しい解決法はconfigを読みに行かせるというよりパラメータの一部を渡せるoptionを追加する
> 
> 
> 
> そうだと思う．あとゆるふわな名前の環境変数読みに行くのは破壊を生みがちなので，やるとしても読むやつは`COMPOSE_CD_`みたいなprefixを付けるとかしたいかなあ．

optionを渡すというのは `compose-cd install --git-pull-user root` みたいな書式で渡すことを想定してるんですが、環境変数読みに行くってのはどこのことを言っていますか？

**Comment by sksat** [comment]
> optionを渡すというのは `compose-cd install --git-pull-user root` みたいな書式で渡すことを想定してるんですが、環境変数読みに行くってのはどこのことを言っていますか？

はい．それを想定してます．「このようにしている」から環境変数を読んでほしいのかと思ったけどそうではないのか(あとこれ「このようにしている(が特になんの効果もない)」，ですよねたぶん)．

**Comment by kory33** [comment]
> あとこれ「このようにしている(が特になんの効果もない)」，ですよねたぶん

そこで貼ったリンクはforkして #27 の 51b00b7 が適用されたものを参照していたので、「 #27 での変更がされたものに対して `export` で定数を渡すようにしている」までを言うべきでした

（今日かなり意思伝達破滅太郎になっとるな　だめそう　すみません）

**Comment by kory33** [comment]
よりまとも度が高いissue(#31)を建てたためこちらはcloseします
