### ISSUE TITLE
.compose-apply で書くパスは相対パスであってほしい(breaking change)

### ISSUE THREAD

**Issue by kory33** [sksat/compose-cd#30]
今のところリポジトリルートからのパスを書かないといけないようになっており、 `.compose-cd` 及び `.compose-apply` がリポジトリのサブディレクトリに置いてある運用だと混乱を招く

参考： https://github.com/GiganticMinecraft/seichi_infra/pull/18#discussion_r780890921

**Comment by sksat** [comment]
これはそうだと思うのでやります

**Comment by sksat** [comment]
@kory33 0.4系で入ります．0.4 branchでテストして貰えると助かる．

**Comment by kory33** [comment]
テスト後でやる

**Comment by kory33** [comment]
実際にインストールして、というところまでやってないけど、変更見た感じまぁ行けるんじゃないでしょうかという感じ

**Comment by sksat** [comment]
ワイトもそう思います

**Comment by sksat** [comment]
閉じ忘れ
