### ISSUE TITLE
WebHook通知のユーザー名をホストごとに変えたい

### ISSUE THREAD

**Issue by yanorei32** [sksat/compose-cd#97]
# Problem
どのホストからの通知か、判別するのが困難。

# Actual Behaviour
![image](https://user-images.githubusercontent.com/11992915/179324204-f8db1b24-6b0e-433f-ac29-dd132b786d2f.png)

まるでわからない。
Discord側にてWebHook名をデフォルトの `Spidey Bot` から変更し指定しても、WebHookリクエストで強制しているためそちらが優先されてしまう。

https://github.com/sksat/compose-cd/blob/2cff105adc2609075770a892f2d1db03ac267c0f/compose-cd#L39-L40

# Workaround
人間が区別できるアイコンをホスト毎に描き、設定することで回避できる。

しかし依然としてIRC Viewには人権がない。(デフォルトではアイコンが表示されず、ユーザー名をクリックする必要がある為)

# Possible Solution
- Configuration fileにusernameのoverrideを設定可能にする
- usernameにホスト名を追加する

等があると嬉しい。

**Comment by sksat** [comment]
あーこれ気付いてなかった．たしかに．

**Comment by sksat** [comment]
あと，僕の場合ホスト毎にチャンネル分けてたから困ってなかったな
